server:
  port: '8082'

spring:
  profiles:
    active: qa

# Spring Boot Query Methods
# https://docs.spring.io/spring-data/jpa/docs/current/reference/html/#reference#

#----------------- H2 DataBase Configuration ----------------
#spring:
#  h2:
#    console:
#      enabled: 'true'
#  datasource:
#    username: lalit
#    url: jdbc:h2:mem:dcbapp
#    driverClassName: org.h2.Driver
#    password: siraswa
#  jpa:
#    database-platform: org.hibernate.dialect.H2Dialect

# --- these (3---) indicates starting of new document
# Dev Profile
---
#----------------- MySql DataBase Configuration ----------------
spring:
  profiles: dev
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3306/dcbapp
    password: ro$iWx4x
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: 'true'
welcome:
  message: Welcome to the world of Programming!!

# QA profile
---
spring:
  profiles: qa
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3306/dcbapp-qa
    password: ro$iWx4x
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: 'true'
welcome:
  message: Welcome to the world of Programming!!

# It includes or enables all the endpoints of /actuator.
management:
  endpoints:
    web:
      exposure:
        include: "*"

# Prod Profile
---
spring:
  profiles: prod
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3306/dcbapp-prod
    password: ro$iWx4x
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: 'true'
welcome:
  message: Welcome to the world of Programming!!